### ISSUE TITLE
When fit (focused) test is used, no other test is reported pending.

### ISSUE THREAD

**Issue by johnjbarton** [bcaudan/jasmine-spec-reporter#142]
I ran a test suite and I got "all green", but when I read closely I see "Ran 1 of 2 specs". Then I recalled that some time ago I set fit() on one test. 

Should non-fit tests be reported pending when at least one test is fit()?

I guess the push back could be that the current fit() UI is clean, adding a bunch of pending tests would clutter the focused UI.

Maybe the summary line:
Executed 1 of 2 specs SUCCESS (1 SKIPPED)
should be different. It seems incorrect to say "SUCCESS" for a fit() case.  Maybe "INCOMPLETE" in yellow unless skippedSpecs and pendingSpecs are zero?  That could be enough to alert a user that they are not done with the suite.

**Comment by bcaudan** [comment]
Hi @johnjbarton!

> Should non-fit tests be reported pending when at least one test is fit()? 

Pending test state is actually handled by jasmine and correspond to these cases:
* test disabled with `xit`
* test disabled by calling `pending()` function

Skipped is a deducted state corresponding to these cases:
* test inside a disabled suite `xdescribe`
* test not focused (`fit` or `fdescribe`)

> I guess the push back could be that the current fit() UI is clean, adding a bunch of pending tests would clutter the focused UI.

IIRC we do not have any information for skipped tests, so we could not display a skipped summary.

> Maybe the summary line:
Executed 1 of 2 specs SUCCESS (1 SKIPPED)
should be different. It seems incorrect to say "SUCCESS" for a fit() case. Maybe "INCOMPLETE" in yellow unless skippedSpecs and pendingSpecs are zero? That could be enough to alert a user that they are not done with the suite.

I agree, display is really not explicit when tests are skipped.

I would go with these two changes:
1. Add color for skipped spec, with the same color as skipped by default
2. Display INCOMPLETE instead of SUCCESS if some specs are not executed.

I would be pleased to review PR for these two points :)

**Comment by bcaudan** [comment]
Available in `jasmine-spec-reporter@4.1.0`
