### ISSUE TITLE
Show progress during testing

### ISSUE THREAD

**Issue by MathRobin** [bcaudan/jasmine-spec-reporter#427]
Hi ! Many thanks for your work firstly !

Actually, this reporter displays things like this :

```
Test widgets
    ✓ user search for a widget's company and see widget page
    ✓ user from company admin page
    ✓ user should not access to widget without valid siren
    ✓ user can see the widgets page
    ✓ user can access the small widget page
    ✓ user can access the reviews widget page
    ✓ user can access the carousel widget page
    ✓ user can access the sticky widget page
    ✓ user can access the facebook widget page
    ✓ user can access the signature widget page
```
It could be great to have an option to be able to display this :
```
Test widgets (2/24)
    ✓ user search for a widget's company and see widget page (1/6)
    ✓ user can see the widgets page (2/6)
    ✓ user can access the small widget page (3/6)
    ✓ user can access the carousel widget page (4/6)
    ✓ user can access the sticky widget page (5/6)
    ✓ user can access the facebook widget page (6/6)
```
The ideal should be to setup it for suites and for tests. Something like this :
```javascript
new HtmlReporter({
      ...,
      suitesProgress: true, // default false
      testsProgress: true // default false
});
```
Is it possible ?

Many thanks in advance for your point of view, your help and again : many thanks for your work !

**Comment by bcaudan** [comment]
Hi @MathRobin!

There is the [displayNumber](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/src/configuration.ts#L8) option to display the suite and test number, output would look like:

``` 
1 Test widgets
    ✓ 1.1 user search for a widget's company and see widget page
    ✓ 1.2 user from company admin page
    ✓ 1.3 user should not access to widget without valid siren
    ✓ 1.4 user can see the widgets page
```
Maybe it could suit your need.

Otherwise, you could [build your own display processor](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/docs/customize-output.md) to do what you want and probably take some inspiration from [the suite numbering processor](https://github.com/bcaudan/jasmine-spec-reporter/blob/master/src/processors/suite-numbering-processor.ts).

**Comment by MathRobin** [comment]
Oh ! Great !

Didn't respond to the whole problem but it's a great stopgap until I had time to push a pull request to suggest a whole solution on my needs.

Again : many thanks !
